#!/usr/bin/env python3
"""Run PyLink with gevent patches enabled."""

import gevent.monkey
gevent.monkey.patch_all()

import sys
try:
    from pylinkirc import launcher
except ImportError:
    print("ERROR: Failed to import PyLink launcher module. Please make sure PyLink is installed correctly.")
    sys.exit(1)
else:
    if __name__ == '__main__':
        launcher.main()
