#!/usr/bin/env python3
"""Run PyLink with gevent patches enabled."""

import gevent.monkey
import gevent.hub
gevent.monkey.patch_all()

# XXX: make this target configurable
gevent.hub.get_hub().exception_stream = open('pylink-discord.log', 'w')

import sys
try:
    from pylinkirc import launcher
except ImportError:
    print("ERROR: Failed to import PyLink launcher module. Please make sure PyLink is installed correctly.")
    sys.exit(1)
else:
    if __name__ == '__main__':
        launcher.main()
